### ISSUE TITLE
Getting java.lang.NoSuchMethodError with latest 4.3.5 version

### ISSUE THREAD

**Issue by pmihalcin** [jbehavesupport/jbehave-junit-support#33]
I have working JBehave test setup using:
`org.jbehavesupport.runner.JUnitRunnerConfiguration.recommendedConfiguration` and `org.jbehavesupport.runner.JUnitRunner`
I use previous version `1.2.7` of this library.
When I update to the latest, i.e. 
```
<dependency>
  <groupId>org.jbehavesupport</groupId>
  <artifactId>jbehave-junit-support</artifactId>
  <version>4.3.5</version>
</dependency>
```
and run any test, I'm getting following exception:

```
java.lang.NoSuchMethodError: org.jbehave.core.embedder.PerformableTree.newRunContext(Lorg/jbehave/core/configuration/Configuration;Ljava/util/List;Lorg/jbehave/core/embedder/EmbedderMonitor;Lorg/jbehave/core/embedder/MetaFilter;Lorg/jbehave/core/failures/BatchFailures;)Lorg/jbehave/core/embedder/PerformableTree$RunContext;

	at org.jbehavesupport.runner.JUnitRunner.createPerformableTree(JUnitRunner.java:139)
	at org.jbehavesupport.runner.JUnitRunner.addStories(JUnitRunner.java:128)
	at org.jbehavesupport.runner.JUnitRunner.buildStoryDescription(JUnitRunner.java:119)
	at org.jbehavesupport.runner.JUnitRunner.<init>(JUnitRunner.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```
When I drill down, I found this:

![image](https://user-images.githubusercontent.com/5480557/52484802-80b70b80-2bb7-11e9-87a5-54728104564b.png)

Any idea what's wrong?

**Comment by mbocek** [comment]
Please check the version of jbehafe. Usually, this kind of errors is connected with the wrong version of jbehave.

**Comment by pmihalcin** [comment]
@mbocek Could you please put some information in a README with which JBehave version is this library compatible?

**Comment by mbocek** [comment]
Good point!
